name: Deploy to cPanel

on:
  push:
    branches:
      - master # Sesuaikan jika nama branch utama Anda bukan master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./ # Folder tujuan (root dari akun FTP yang sudah dikunci)
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            config.php
